name: Publish to RubyGems
on:
  release:
    types: [created]
jobs:
  gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - run: sed -i "s/0.0.1/$(echo $GITHUB_REF_NAME | cut -c 2-)/" lib/pixelpress/version.rb
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
